---
title: "Final Report"
author: "Group Name"
date: "May 3, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


The final project report will contain the following sections:

##Section 1 Analytics Question/Problem (5 pts.) 

The analytics question/problem being addressed. In your framing of the analytics question, please state clearly articulate: 

a.	The specific predictive analytic question you are attempting to answer, or problem you are trying to solve? Since this course is about predictive analytics, it is important that you clearly specify the response variable you are predicting. 

b.	What type of problem or question you are addressing – i.e., quantitative or classification 

c.	What your analytics goal(s) is(are) – i.e., inference, interpretation and/or prediction. 

##Section 2 Business Rational (10 pts.)

A brief but compelling business rationale about the importance of this question/problem from a business perspective. Why is the problem you are analyzing important? 

##Section 3 Description of the Data (10 pts.) 

A description of the data set utilized for the analysis (if the data set is not available in an R package or public web site, the data set must be attached). Your data description should be sufficient for your reading audience to understand your data set, variables and the interpretations you provide in your report, including variable types and units of measurement. The data description should be accompanied by any necessary descriptive analytics artifacts necessary for your predictive modeling (e.g., descriptive statistics, correlation matrix, correlation plots, other plots, etc.). 

##Section 4 Pre-Processing	 (10 pts.) 

A discussion of any pre-processing (e.g., grouping, combining variables, etc.) and transformations done with the data (e.g., normality, logs, standardization, non-linear, etc.), along with the rationale for the appropriateness of this transformation. 

##Section 5 Model Justification (20 pts.) 

A justification for the analytics methods and model specifications used. All methods used must be appropriate and relevant to the problem and you need to provide a justification for the selected methods based on: 

a.	Conformance with or departure from OLS assumptions; If you are using OLS as one of your methods, you must test key OLS assumptions. If you don’t plan to use the OLS model, you need to specify which OLS assumption would be violated. 

b.	Analysis goals (i.e., inference, interpretation and/or accuracy); you must specify your analysis goal(s). 

c.	Predictive accuracy based on cross-validation test statistics. Similarly, the particular model specifications utilized must have a rationale. For example, if you chose a quadratic regression specification, you must have some rationale for the respective non-linear relationship. All projects must be analyzed with a variety of appropriate model with different model specification. Please consult with me if in doubt, but these are the minimum requirements 

All projects must evaluate 3 different methods, with 2 different model specifications for each. You need to provide in this section a sound justification for your choice of models to evaluate. 

##Section 6 Analysis of Results	 (20 pts.) 

Analysis and presentation of results. Your analysis and results need to contain some narrative to allow your audience to understand what you did. A simple output and diagram dump with no explanation will receive very little credit. Every procedure, output and diagram needs to be briefly but appropriately introduced before and briefly commented on its meaning after. Don’t leave it up to the reader to interpret what you did. 

##Section 7 Conclusion	(15 pts.) 

A short section with final thoughts, conclusions and lessons learned. These conclusions must contain a discussion of: 

a.	Your final model method and specification selection. Why did you pick this particular modeling method and model specification. 

b.	The main conclusions of your analysis. These conclusions must answer/solve your analytics question/problem stated in 1 above. Please be brief but concise and discuss the main insights you obtained from your analysis 

c.	A brief statement of your lessons learned in this project in terms of: data issues, methodological challenges, do's and don'ts, what you learned from this experience. You don't need to address all of this. But please be thoughtful and make it interesting. 


##Section 8 Writng Quality Formatting and Presentation (Not in Paper) (10 pts.) 

Writing Quality, Formatting and Presentation. Analytics projects, no matter how good, are not very useful unless the analytics report is well written and clearly articulated. Nobody wants to see a bunch of statistical output without sound commentary about the results and their implications for business. Consequently, heavy weight will be placed on the attractiveness, presentation, writing clarity of the report, free of grammatical errors and typos. More importantly, the entire report needs to flow and be understandable to your audience. 

##Other Requirements: 

(1) all R code and R output/graphics must be visible in the knitted R Markdown HTML or R Presentation file; 
(2) the data used set must also be submitted or made available by other means; and 
(3) the written material in the report should be about 1500 words long (approx. 3 pages single-spaced).

